---
title: "big_visualization"
output: html_document
date: "2024-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# imports
library(ggplot2)
library(gggenomes)
library(cowplot)
library(aplot)
library(dplyr)
```

## R Markdown
```{r}
y <- c("D_sordidapex", "D_conformis", "D_incognita", "D_percnosoma", "D_neutralis", "D_atroscutellata", "D_trichaetosa", "D_imparisetae", "D_kupee", "D_kuia", "D_seclusa", "D_nigritarsus", "D_nr_medialis", "D_paracracens", "D_cracens", "D_nr_fundita", "D_kokeensis", "D_tanythrix", "D_yooni", "D_cognata", "D_kambysellisi", "D_infuscata", "D_mimica", "D_melanosoma", "D_fulgida", "D_fungiperda", "D_longiperda", "D_multiciliata", "D_demipolita", "D_dives", "D_sproati", "D_murphyi", "D_ochracea", "D_villosipedis", "D_engyochracea", "D_pullipes", "D_grimshawi", "D_crucigera", "D_hawaiiensis", "D_macrothrix", "D_glabriapex", "D_paucipunta", "D_basisetae", "D_prolacticillia", "D_paucipuncta", "D_picticornis", "D_silvestris", "D_heteroneura", "D_planitibia", "D_differens", "D_melanocephala", "D_cyrtoloma", "D_quasianomalipes", "D_anomalipes", "D_setosimentum", "D_primaeva", "S_tumidula", "S_cyrtandrae", "S_reducta", "S_pallida", "S_parva", "S_caliginosa", "S_montana", "S_flava", "S_graminum", "S_polygonia", "S_hsui", "D_flavopinicola", "D_maculinotata", "D_arizonae", "D_mojavensis", "D_navojoa", "D_mulleri", "D_aldrichi", "D_mayaguana", "D_hamatofila", "D_buzzatii", "D_koepferae", "D_stalkeri", "D_meridionalis", "D_meridiana", "D_repleta", "D_mercatorum", "D_paranaensis", "D_peninsularis", "D_fulvimacula", "D_nigricruria", "D_anceps", "D_leonis", "D_pegasa", "D_hydei", "D_eohydei", "D_mettleri", "D_gaucha", "D_pachea", "D_nannoptera", "D_pseudotalamancana", "D_americana_texana", "D_americana", "D_novamexicana", "D_virilis", "D_kanekoi", "D_ezoana", "D_littoralis", "D_flavomontana", "D_borealis", "D_lacicola", "D_colorata", "D_sordidula", "D_micromelanica", "D_paramelanica", "D_lacertosa", "H_histrioides", "H_confusa", "H_alboralis", "H_cameraria", "Z_flavofinira", "H_trivittata", "D_recens", "D_subquinaria", "D_suboccidentalis", "D_guttifera", "D_quinaria", "D_rellima", "D_innubila", "D_falleni", "D_phalerata", "D_kuntzei", "D_histrio", "D_testacea", "D_neotestacea", "D_putrida", "D_macrospina", "D_funebris", "D_nigrodunni", "D_arawakana", "D_dunni", "D_acutilabella", "D_parthenogenetica", "D_cardini", "D_tripunctata", "D_pallidipennis", "D_nasuta", "D_albomicans", "D_kepulauana", "D_pallidifrons", "D_kohkoa", "D_sulfurigaster", "D_sulfurigaster_sulfurigaster", "D_sulfurigaster_bilimbata", "D_sulfurigaster_albostrigata", "D_niveifrons", "D_neohypocausta", "D_siamana", "D_hypocausta", "D_rubida", "D_ustulata", "D_formosana", "D_immigrans", "D_pruinosa", "D_quadrilineata", "Z_nigranus", "Z_camerounensis", "Z_lachaisei", "Z_vittiger", "Z_davidi", "Z_taronus", "Z_capensis", "Z_indianus", "Z_gabonicus", "Z_africanus", "Z_ornatus", "Z_tuberculatus", "Z_tsacasi", "Z_kolodkinae", "Z_inermis", "Z_ghesquierei", "Z_bogoriensis", "L_aerea", "H_guttata", "D_repletoides", "D_busckii", "D_yakuba", "D_santomea", "D_teissieri", "D_orena", "D_erecta", "D_simulans", "D_sechellia", "D_mauritiana", "D_melanogaster", "D_eugracilis", "D_pseudotakahashii", "D_prostipennis", "D_lutescens", "D_takahashii", "D_mimetica", "D_suzukii", "D_subpulchrella", "D_biarmipes", "D_ficusphila", "D_prolongata", "D_rhopaloa", "D_carrolli", "D_fuyamai", "D_kurseongensis", "D_gunungcola", "D_elegans", "D_oshimai", "D_mayri", "D_birchii", "D_truncata", "D_bicornuta", "D_serrata", "D_bunnanda", "D_bocqueti", "D_aff_chauvacae_bk", "D_vulcana", "D_seguyi", "D_jambulina", "D_punjabiensis", "D_kikkawai", "D_bocki", "D_kanapiae", "D_lacteicornis", "D_asahinai", "D_rufa", "D_tani", "D_triauraria", "D_pectinifera", "D_malerkotliana_pallens", "D_malerkotliana_malerkotliana", "D_parabipectinata", "D_bipectinata", "D_pseudoananassae", "D_pseudoananassae_pseudoananassae", "D_pseudoananassae_nigrens", "D_pallidosa", "D_ananassae", "D_anomalata", "D_pandora", "D_monieri", "D_atripex", "D_ercepeae", "D_merina", "D_vallismaia", "D_varians", "D_ironensis", "D_setifemur", "D_pseudoobscura", "D_pseudoobscura_pseudoobscura", "D_persimilis", "D_miranda", "D_lowei", "D_athabasca", "D_algonquin", "D_affinis", "D_azteca", "D_helvetica", "D_tristis") 
       
z <- c("D_ambigua", "D_obscura", "D_subsilvestris", "D_bifasciata", "D_subobscura", "D_guanche", "D_paulistorum", "D_equinoxialis", "D_willistoni", "D_tropicalis", "D_insularis", "D_nebulosa", "D_sucinea", "D_sp_14030", "D_prosaltans", "D_austrosaltans", "D_saltans", "D_emarginata", "D_neocordata", "D_sturtevanti", "L_clarofinis", "L_sp_2_aff_clarofinis", "L_sp_3", "L_magnipectinata", "L_andalusiaca", "L_fenestrarum", "L_collinella", "L_mommai", "H_duncani", "S_latifasciaeformis", "C_fuscimana", "C_costata", "C_amoena", "C_procnemis", "C_caudatula", "S_lebanonensis", "A_mariae", "A_communis", "A_minor", "C_indagator", "L_montana", "L_maculata", "L_varia", "S_nigrithorax")
x <- c(y,z)
#plus
data.list <- list()
c <- 1
for (n in x) {
  m0 <- read.table(file = paste("gene_name/results/plus/", n, "_genes_plus_500_upstream.csv", sep= ""), sep = '\t', header = TRUE)
  m0$seqID[0:length(m0$seqID)] <- n
  colnames(m0)[1] <- "seq_id"
  m0$start <- 500 - m0$start
  m0$end<- 500 - m0$end
  data.list[[c]] <- assign(paste0("plus", n), m0)
  c <- c + 1
}
#minus
for (n in x) {
  m0 <- read.table(file = paste("gene_name/results/minus/", n, "_genes_minus_500_upstream.csv", sep= ""), sep = '\t', header = TRUE)
  m0$seqID[0:length(m0$seqID)] <- n
  colnames(m0)[1] <- "seq_id"
  data.list[[c]] <- assign(paste0("minus", n), m0)
  c <- c + 1
}

big_data <- do.call(rbind, data.list)
l0 <- read.csv("/workdir/table.csv")

 
q <- gggenomes(big_data, l0) +
  geom_seq() +
  geom_seq_label(size = 2) +
  scale_x_reverse() +
  geom_gene(aes(fill = patternName), position = "strand", size = 2) +
  theme(axis.title.x = element_text(size = 10)) +
  labs(x = "Bases from Gene Start Site", size = 10) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("gene_name")
ggsave("gene_name.png", q, width = 12, height = 30, dpi = 300)
```


